# Generated by Django 3.2.8 on 2021-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=300)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
