# Generated by Django 3.2.8 on 2021-10-12 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.date(2021, 10, 12), verbose_name='date published'),
        ),
    ]
